# 非 split 右手検証用（バッテリー報告オフ + RGB + トラックボール / エンコーダ）

CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_PMW3610=y

CONFIG_ZMK_BATTERY_REPORTING=n
CONFIG_RGBLED_WIDGET_BATTERY_SHOW_SELF=y
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_LOW=10
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=30
